# Generated by Django 4.2.2 on 2023-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.9, max_digits=20),
        ),
    ]
